package io.github.acedroidx.shark7.model

import android.media.AudioAttributes

enum class MyAudioAttributes(val value: Int) {
    USAGE_ALARM(AudioAttributes.USAGE_ALARM),
    USAGE_ASSISTANCE_ACCESSIBILITY(AudioAttributes.USAGE_ASSISTANCE_ACCESSIBILITY),
    USAGE_ASSISTANCE_NAVIGATION_GUIDANCE(AudioAttributes.USAGE_ASSISTANCE_NAVIGATION_GUIDANCE),
    USAGE_ASSISTANCE_SONIFICATION(AudioAttributes.USAGE_ASSISTANCE_SONIFICATION),
    USAGE_ASSISTANT(AudioAttributes.USAGE_ASSISTANT),
    USAGE_NOTIFICATION(AudioAttributes.USAGE_NOTIFICATION),
    USAGE_NOTIFICATION_EVENT(AudioAttributes.USAGE_NOTIFICATION_EVENT),
    USAGE_NOTIFICATION_RINGTONE(AudioAttributes.USAGE_NOTIFICATION_RINGTONE),
}